// The ~100 largest cities in the world (by urban-area / metro population,
// roughly ordered). The mission picker draws 8 at random from this list to
// populate the mission-select tiles — those 8 become the submarine's missions.
export const WORLD_CITIES: string[] = [
  'Tokio',
  'Delhi',
  'Shanghái',
  'Daca',
  'São Paulo',
  'Ciudad de México',
  'El Cairo',
  'Pekín',
  'Bombay',
  'Osaka',
  'Karachi',
  'Chongqing',
  'Estambul',
  'Buenos Aires',
  'Calcuta',
  'Lagos',
  'Kinsasa',
  'Manila',
  'Tianjin',
  'Cantón',
  'Río de Janeiro',
  'Lahore',
  'Bangalore',
  'Shenzhen',
  'Moscú',
  'Chennai',
  'Bogotá',
  'Yakarta',
  'Lima',
  'París',
  'Bangkok',
  'Hyderabad',
  'Seúl',
  'Nankín',
  'Chengdú',
  'Londres',
  'Luanda',
  'Teherán',
  'Ho Chi Minh',
  'Nagoya',
  "Xi'an",
  'Ahmedabad',
  'Wuhan',
  'Kuala Lumpur',
  'Hangzhou',
  'Suzhou',
  'Surat',
  'Dar es-Salam',
  'Nueva York',
  'Bagdad',
  'Shenyang',
  'Riad',
  'Hong Kong',
  'Foshan',
  'Dongguan',
  'Pune',
  'Santiago',
  'Madrid',
  'Harbin',
  'Toronto',
  'Johannesburgo',
  'Belo Horizonte',
  'Jartum',
  'Qingdao',
  'Dalian',
  'Singapur',
  'Chittagong',
  'Abiyán',
  'Barcelona',
  'Ankara',
  'Rangún',
  'Alejandría',
  'Jinan',
  'Guadalajara',
  'Kabul',
  'Zhengzhou',
  'Berlín',
  'Adís Abeba',
  'Nairobi',
  'Casablanca',
  'Ciudad del Cabo',
  'Yeda',
  'Changsha',
  'Kanpur',
  'Xiamen',
  'Kunming',
  'Tel Aviv',
  'Roma',
  'Los Ángeles',
  'Medellín',
  'Nanchang',
  'Faisalabad',
  'Wenzhou',
  'Hefei',
  'Fukuoka',
  'Monterrey',
  'Recife',
  'Porto Alegre',
  'Salvador',
  'Sídney',
];

// Pick n distinct random cities (partial Fisher–Yates shuffle).
export function pickRandomCities(n: number): string[] {
  const a = [...WORLD_CITIES];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a.slice(0, n);
}
