// Country flag code for each city in WORLD_CITIES, used by the admin "Ciudades"
// view to show a little flag next to each name. Keyed by the EXACT Spanish city
// string used in cities.ts (accents/apostrophe included). Values are
// flag-icons codes (ISO 3166-1 alpha-2, lowercase) so we can render real SVG
// flags with `<span class="fi fi-{code}">` — these look the same on every
// browser/OS (unlike flag emoji, which don't render on Windows Chrome/Edge).
// A missing city degrades gracefully: the name still shows, just no flag.
const CITY_COUNTRY: Record<string, string> = {
  Tokio: 'jp',
  Delhi: 'in',
  Shanghái: 'cn',
  Daca: 'bd',
  'São Paulo': 'br',
  'Ciudad de México': 'mx',
  'El Cairo': 'eg',
  Pekín: 'cn',
  Bombay: 'in',
  Osaka: 'jp',
  Karachi: 'pk',
  Chongqing: 'cn',
  Estambul: 'tr',
  'Buenos Aires': 'ar',
  Calcuta: 'in',
  Lagos: 'ng',
  Kinsasa: 'cd',
  Manila: 'ph',
  Tianjin: 'cn',
  Cantón: 'cn',
  'Río de Janeiro': 'br',
  Lahore: 'pk',
  Bangalore: 'in',
  Shenzhen: 'cn',
  Moscú: 'ru',
  Chennai: 'in',
  Bogotá: 'co',
  Yakarta: 'id',
  Lima: 'pe',
  París: 'fr',
  Bangkok: 'th',
  Hyderabad: 'in',
  Seúl: 'kr',
  Nankín: 'cn',
  Chengdú: 'cn',
  Londres: 'gb',
  Luanda: 'ao',
  Teherán: 'ir',
  'Ho Chi Minh': 'vn',
  Nagoya: 'jp',
  "Xi'an": 'cn',
  Ahmedabad: 'in',
  Wuhan: 'cn',
  'Kuala Lumpur': 'my',
  Hangzhou: 'cn',
  Suzhou: 'cn',
  Surat: 'in',
  'Dar es-Salam': 'tz',
  'Nueva York': 'us',
  Bagdad: 'iq',
  Shenyang: 'cn',
  Riad: 'sa',
  'Hong Kong': 'hk',
  Foshan: 'cn',
  Dongguan: 'cn',
  Pune: 'in',
  Santiago: 'cl',
  Madrid: 'es',
  Harbin: 'cn',
  Toronto: 'ca',
  Johannesburgo: 'za',
  'Belo Horizonte': 'br',
  Jartum: 'sd',
  Qingdao: 'cn',
  Dalian: 'cn',
  Singapur: 'sg',
  Chittagong: 'bd',
  Abiyán: 'ci',
  Barcelona: 'es',
  Ankara: 'tr',
  Rangún: 'mm',
  Alejandría: 'eg',
  Jinan: 'cn',
  Guadalajara: 'mx',
  Kabul: 'af',
  Zhengzhou: 'cn',
  Berlín: 'de',
  'Adís Abeba': 'et',
  Nairobi: 'ke',
  Casablanca: 'ma',
  'Ciudad del Cabo': 'za',
  Yeda: 'sa',
  Changsha: 'cn',
  Kanpur: 'in',
  Xiamen: 'cn',
  Kunming: 'cn',
  'Tel Aviv': 'il',
  Roma: 'it',
  'Los Ángeles': 'us',
  Medellín: 'co',
  Nanchang: 'cn',
  Faisalabad: 'pk',
  Wenzhou: 'cn',
  Hefei: 'cn',
  Fukuoka: 'jp',
  Monterrey: 'mx',
  Recife: 'br',
  'Porto Alegre': 'br',
  Salvador: 'br',
  Sídney: 'au',
};

// Spanish country name per flag-icons code, so the flag's tooltip can say the
// country instead of repeating the city name.
const COUNTRY_NAME: Record<string, string> = {
  jp: 'Japón',
  in: 'India',
  cn: 'China',
  bd: 'Bangladés',
  br: 'Brasil',
  mx: 'México',
  eg: 'Egipto',
  pk: 'Pakistán',
  tr: 'Turquía',
  ar: 'Argentina',
  ng: 'Nigeria',
  cd: 'RD del Congo',
  ph: 'Filipinas',
  ru: 'Rusia',
  co: 'Colombia',
  id: 'Indonesia',
  pe: 'Perú',
  fr: 'Francia',
  th: 'Tailandia',
  kr: 'Corea del Sur',
  gb: 'Reino Unido',
  ao: 'Angola',
  ir: 'Irán',
  vn: 'Vietnam',
  my: 'Malasia',
  tz: 'Tanzania',
  us: 'Estados Unidos',
  iq: 'Irak',
  sa: 'Arabia Saudita',
  hk: 'Hong Kong',
  cl: 'Chile',
  es: 'España',
  ca: 'Canadá',
  za: 'Sudáfrica',
  sd: 'Sudán',
  sg: 'Singapur',
  ci: 'Costa de Marfil',
  mm: 'Birmania',
  af: 'Afganistán',
  de: 'Alemania',
  et: 'Etiopía',
  ke: 'Kenia',
  ma: 'Marruecos',
  il: 'Israel',
  it: 'Italia',
  au: 'Australia',
};

// flag-icons code for a city (e.g. "mx"), or '' if we have no mapping for it.
export function cityFlagCode(city: string): string {
  return CITY_COUNTRY[city.trim()] ?? '';
}

// Spanish country name for a city (used as the flag's tooltip), or '' if
// unmapped.
export function cityCountry(city: string): string {
  return COUNTRY_NAME[cityFlagCode(city)] ?? '';
}
